name: plantdoctor
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.*
  - pandas=2.1.*
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - streamlit
  - flask
  - pillow
  - requests
  - pymongo
  - cryptography
  - bcrypt
  - pip
  - pip:
      - python-dotenv
      - google-generativeai
      - google-cloud-aiplatform
      - transformers
      - langchain